Fix build break on 64 bits architectures.
- error: 'SYS_sigaction' was not declared in this scope
  Aarch64/x64 is missing the "SYS_sigaction" definition.
  Replace "SYS_sigaction" used in thread synchronization code with "SYS_rt_sigaction".

- error: invalid cast from type 'SecurityManager::IStream' to type 'long unsigned int'
  revert to previous implementation

Change-Id: I58041f66c988934d5577daf7a574bb7b9a2b394a